### ISSUE TITLE
Cannot use "::class" on value of type null

### ISSUE THREAD

**Issue by ramakrishnamie** [ryangjchandler/filament-feature-flags#2]
This issue existed after the installation of require chiiya/filament-access-control package.

**Comment by ryangjchandler** [comment]
@ramakrishnamie I don't promise to support integration with other packages. If you're able to `dd()` the value of `$record` inside of that callback, it might help.

**Comment by SebastiaanKloos** [comment]
@ryangjchandler I just have the same issue. It's when creating a feature with a model but without selecting a resource. Then when going to the index page shows this error.

**Comment by ryangjchandler** [comment]
This package is designed to work with resources registered with Filament, the README has documentation showing how to setup the resource. 

I suppose it could work on normal models too... perhaps I should change it to show a list of models instead.

**Comment by SebastiaanKloos** [comment]
> This package is designed to work with resources registered with Filament, the README has documentation showing how to setup the resource. 
> 
> 
> 
> I suppose it could work on normal models too... perhaps I should change it to show a list of models instead. 

@ryangjchandler I think that the record should be required when you select a model. Your solution would also work but I think it's not really needed

**Comment by ryangjchandler** [comment]
Yeah, it's just a change in the validation rules, doing a conditional `required()` rule.

**Comment by SebastiaanKloos** [comment]
Should be fixed by #6
