### ISSUE TITLE
When changing a feature from specific model / resource to global, the resource index page crashes when `flaggable_id` is not null

### ISSUE THREAD

**Issue by SebastiaanKloos** [ryangjchandler/filament-feature-flags#5]

**Comment by ryangjchandler** [comment]
@SebastiaanKloos could your provide a code example please? I assume you're setting the same flag on a model AND a global flag with the same name?

**Comment by SebastiaanKloos** [comment]
> @SebastiaanKloos could your provide a code example please? I assume you're setting the same flag on a model AND a global flag with the same name?

No it's when you change a model feature flag to global by deselecting a model. The flaggable_id is still filled with a record ID and crashes. I'll make a PR.

**Comment by ryangjchandler** [comment]
Sure.

**Comment by SebastiaanKloos** [comment]
Should be fixed by #6
